server:
  http:
    addr: 0.0.0.0:${HTTP_PORT:8000}
    timeout: 30s
  grpc:
    addr: 0.0.0.0:${GRPC_PORT:9000}
    timeout: 30s

data:
  database:
    driver: mysql
    source: ${DB_USER:root}:${DB_PASSWORD:jKBrZHGcsNG5fMc52EWz}@tcp(${DB_HOST:localhost}:${DB_PORT:3306})/${DB_NAME:demo_project}?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: ${REDIS_HOST:localhost}:${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    db: ${REDIS_DB:0}
    pool_size: 100
    read_timeout: 0.2s
    write_timeout: 0.2s
  object_storage:
    provider: ${OBJECT_STORAGE_PROVIDER:minio} # s3, oss, cos, minio
    endpoint: ${OBJECT_STORAGE_ENDPOINT:localhost:9000}
    access_key_id: ${OBJECT_STORAGE_ACCESS_KEY:minioadmin}
    secret_access_key: ${OBJECT_STORAGE_SECRET_KEY:minioadmin}
    bucket_name: ${OBJECT_STORAGE_BUCKET:demo}
    region: ${OBJECT_STORAGE_REGION:us-east-1}
    use_ssl: false # Override via OBJECT_STORAGE_USE_SSL env var (set to "true" or "false" as string)
    path_prefix: ${OBJECT_STORAGE_PATH_PREFIX:data/}
    enabled: false # Default disabled, enable manually if needed. Override via OBJECT_STORAGE_ENABLED env var (set to "true" or "false" as string)

log:
  # Log levels: debug(-1), info(0), warn(1), error(2), dpanic(3), panic(4), fatal(5)
  level: -1
  # Format: json or console
  format: console
